# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

      jobs:
        build:

          runs-on: ubuntu-latest

          strategy:
            matrix:
              node-version: [16.x]

          steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: Use Node.js ${{ matrix.node-version }}
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
            - run: npm install --no-audit
            - run: npm run build
            - run: ls dist

            - uses: shallwefootball/s3-upload-action@master
            - name: Upload S3
              with:
                aws_key_id: ${{ secrets.AWS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws_bucket: ${{ secrets.AWS_BUCKET }}
                source_dir: 'dist/index.html'
